config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_lvim:
    src: config/lvim
    dst: ~/.config/lvim
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  d_fish:
    src: config/fish
    dst: ~/.config/fish
    chmod: '700'
profiles:
  devenv:
    dotfiles:
    - d_bspwm
    - d_polybar
    - d_lvim
    - d_kitty
    - d_sxhkd
    - d_fish
